### ISSUE TITLE
Maybe there is an error in the README.rst

### ISSUE THREAD

**Issue by B2RJ** [akretion/factur-x#11]
Hello, 

It's just for information, in the Usage section of the README.rst file it's written to use 
`from facturx import generate_facturx`
`facturx_pdf_invoice = generate_facturx(regular_pdf_invoice, facturx_xml_file)`

But, after testing, it seems we have to use 
`from facturx import generate_facturx_from_file`
`facturx_pdf_invoice = generate_facturx_from_file("MacroPDF.pdf", xml_root)`

**Comment by alexis-via** [comment]
Thanks. Fixed in my next commit.
