### ISSUE TITLE
Unicode strings with encoding declaration are not supported. (Py3?)

### ISSUE THREAD

**Issue by lasalesi** [akretion/factur-x#13]
Hi all,

I have an XML which is rendered from a code generator. In Python 2.7, everything was running fine. Now, after an upgrade to Python 3.5, running

    check_facturx_xsd(facturx_xml=xml)

will fail with _Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration_. I can resolve this by using

    check_facturx_xsd(facturx_xml=xml.encode('utf-8'))

Then, the validation passes fine. However, 

    generate_facturx_from_binary(pdf, xml)

will again fail with the same _Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration_ Passing an encoded byte array will fail by saying it required a string, file or etree object.

Is this a known Python 3.5 issue?

**Comment by hvbtup** [comment]
I think the error message is quite clear. It just makes no sense to have an encoding declaration when you already have decoded the (binary) XML data to text - the encoding declaration could differ from the actual encoding that was used to decode the file.
