### ISSUE TITLE
Add support for python 3.5 / ubuntu 16-04 LTS

### ISSUE THREAD

**Issue by pfxx** [akretion/factur-x#18]
Bonjour,

J'utilise factur-x sur un ubuntu 16-04 qui utilise python 3.5.  
La librairie fonctionne très bien en 3.5 mais déclare nécessiter python >= 3.6

Pourriez vous activer le support py3.5 ?

Dans setup.py, ajouter 
        'Programming Language :: Python :: 3.5',

Cordialement,

**Comment by bealdav** [comment]
Bonjour,

Merci de faire une PR

**Comment by pfxx** [comment]
Ok je m'en occupe

Bonne journée

**Comment by bealdav** [comment]
Pardon mais a la reflexion c peut être pas une bonne idée car on a pas de tests dessus donc vaut mieux parier sur des LTS récentes.
Il faut réduire les couts de maintenance. Python est en 3.8 désormais

Envisagez de passer sur 20.04 et en attendant un petit fork fera l'affaire

Desolé

**Comment by pfxx** [comment]
Pour l'instant Ubuntu 16.04 LTS est encore supporté et donc son python 3.5 toujours bien vivant.
Changer pour du 20.04, effectivement ça viendra

La bonne idée ? la votre :  un fork 👍 qui satisfera tout le monde.

Merci pour votre retour

**Comment by bealdav** [comment]
From

https://www.python.org/dev/peps/pep-0478


    3.5.8 candidate 2: October 12, 2019
    3.5.8 final: October 29, 2019
    3.5.9 final: November 1, 2019

There are no specific plans for the next release of Python 3.5.

3.5 can't be the choice version for this package ;-)
