### ISSUE TITLE
Error in programming logic

### ISSUE THREAD

**Issue by JordyScript** [akretion/factur-x#19]
I had a look through the source code to learn more about PyPDF4 usage, and found line 206 in facturx.py to be suspicious. It looks like a logical error, and hence a bug. 

Apparently the intent of the `level` parameter is to limit recursion depth, but as it stands the line in question does no such thing.

```python
def _parse_embeddedfiles_kids_node(kids_node, level, res):
    ... # lines omitted
       _parse_embeddedfiles_kids_node(kids_node_l2, 2, res)
```
This is the line in the fuction `_parse_embeddedfiles_kids_node` that does the recursion, but instead of dynamically increasing the 2nd argument, `level` is hardcoded as being 2.

The following line would fix the bug. 
```python
_parse_embeddedfiles_kids_node(kids_node_l2, level + 1, res)
```

Unless I have misunderstood the code, I think this problem exists and can be fixed in the manner I suggested.

**Comment by alexis-via** [comment]
I confirm the code. Your suggestion would not change anything because we are in a if with level==1.
