### ISSUE TITLE
ZUGFeRD Schema not existing 

### ISSUE THREAD

**Issue by ahrrikis** [akretion/factur-x#2]
Hi,

I think following line has not been converted to current folder structure. 
https://github.com/akretion/factur-x/blob/3eaf3852cd9854bdf70d5ed7fb9d3145c01ae7d4/facturx/facturx.py#L122

Thanks
Eric

**Comment by alexis-via** [comment]
Has been fixed some time ago, but forgot to close this bug report.
Thanks for reporting the problem.
