### ISSUE TITLE
flateEncode() conflict with PDF integrated signature (eIDAS )

### ISSUE THREAD

**Issue by scaf13** [akretion/factur-x#25]
Bonjour,

Depuis la mise à jour 1.12 et notamment ce commit https://github.com/akretion/factur-x/commit/c182e1fefd1575d0b49473e59b776dacf852a61b (et plus particulièrement les 3 insertions dans facturx/facturx.py), quand j'appose une signature certifiée eIDAS (intégrée au PDF) sur une factur-x, je perds la conformité PDF/A-3.

En empêchant flateEncode(), ma factur-x signée électroniquement est de nouveau valide PDF/A-3.

Serait t'il possible d'avoir une option dans generate_from_file() pour désactiver cette compression ?

Merci pour votre travail.

**Comment by scaf13** [comment]
Closed : https://github.com/akretion/factur-x/pull/23

**Comment by alexis-via** [comment]
If I understand correctly:
1) you generate a PDF/A
2) you attach factur-x.xml with this lib
=> here, the document is still PDF/A valid
3) you add an eIDAS signature
=> it is not PDF/A valid any more

Did I understand correctly ?

**Comment by scaf13** [comment]
Yes, this is right.

Removing the 3 flateEncode assertions in /usr/local/lib/python3.8/dist-packages/facturx works.

**Comment by alexis-via** [comment]
Which tool do you use for the eIDAS signature ?
