### ISSUE TITLE
I have a PDF file with a discount and unit price, why doesn't that field get reflected when it's converted into XML? (pdf to xml )

### ISSUE THREAD

**Issue by rinaharry** [akretion/factur-x#37]
[202312058031220232600003689pdf.pdf](https://github.com/akretion/factur-x/files/13769127/202312058031220232600003689pdf.pdf)

I have a PDF file with a discount and unit price, why doesn't that field get reflected when it's converted into XML?

**Comment by rinaharry** [comment]
@alexis-via @attrib

**Comment by alexis-via** [comment]
When you look at the XML file inside the PDF, you will see that the price without discount is not written in the XML ; they only put the net price. The could have done it differently in the XML.
Anyway, your question is not related to the factur-x python lib. So please report this issue to the company that generated the invoice.
