### ISSUE TITLE
FNFE validator loops forever on Factur-X XML without namespace aliases

### ISSUE THREAD

**Issue by jgag-qonto** [akretion/factur-x#46]
Hi @alexis-via, could you please confirm that the FNFE validator uses the `facturx-xmlcheck` script ?

There is an issue with our Factur-X XMLs, as we generate them with absolute namespaces, without aliases (rsm, ram, udt etc):
```
$ head absolute-ns-factur-x.xml
<CrossIndustryInvoice xmlns="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100">
  <ExchangedDocumentContext xmlns="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100">
    <GuidelineSpecifiedDocumentContextParameter xmlns="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100">
      <ID xmlns="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100">urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic</ID>
```

And the validator from FNFE loops forever:
![Screenshot 2024-11-14 at 13 50 39](https://github.com/user-attachments/assets/b165e5a9-e638-4d74-925a-6f5e18c76b83)

You can [download the full XML file here](https://drive.google.com/file/d/1wpeczWep4j0gjJRy90HaUBZJozCgo1RO/view?usp=sharing)

They validate the official FNFE XSD:
```
$ xmllint --schema ~/Downloads/_Factur-X\ 1.0.06\ 2022\ 03\ 01\ -\ FINAL\ FR/4.\ FACTUR-X_1.0.06_XSD_SCHEMATRON\ -\ 2022\ 03\ 01/2.\ Factur-X_1.0.06_BASIC_XSD/FACTUR-X_BASIC.xsd ./absolute-ns-factur-x.xml --noout
./absolute-ns-factur-x.xml validates
```

They validate the `facturx-xmlcheck` tool, **when the Factur-X level is specified** on the command line:
```
$ facturx-xmlcheck --facturx-level=basic ./absolute-ns-factur-x.xml
/opt/homebrew/bin/facturx-xmlcheck:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('factur-x==3.1', 'facturx-xmlcheck')
2024-11-14 14:01:06,492 [INFO] Flavor is factur-x (autodetected)
2024-11-14 14:01:06,493 [INFO] factur-x XML file successfully validated against XSD
```

But they don't pass the level autodetection if no level is specified:
```
$ facturx-xmlcheck ./absolute-ns-factur-x.xml
/opt/homebrew/bin/facturx-xmlcheck:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('factur-x==3.1', 'facturx-xmlcheck')
2024-11-14 14:01:39,544 [INFO] Flavor is factur-x (autodetected)
2024-11-14 14:01:39,544 [ERROR] empty namespace prefix is not supported in XPath
```

From what we understand, it has something to do with hardcoded namespaces aliases in `get_level()`:
```
"//rsm:SpecifiedExchangedDocumentContext"
"/ram:GuidelineSpecifiedDocumentContextParameter"
"/ram:ID"
```

Do you think it would fix the FNFE validator looping forever, if the hardcoded paths would be fixed so that they also work with absolute namespaces?

**Comment by jgag-qonto** [comment]
I have opened [this MR](https://github.com/akretion/factur-x/pull/47/files) to fix the problem related to the autodetection of facturx-level, hoping it also fixes the FNFE validator looping forever

**Comment by alexis-via** [comment]
@jgag-qonto I fixed the crash in FNFE's factur-x validator, cf this commit https://github.com/akretion/factur-x-validator/commit/17c1b6c70ae428da7b94fcaebeb1e0ac13c07a90
The FNFE validator doesn't use facturx-xmlcheck script ; it uses the factur-x lib and there are some similarities in the code.
I'm not an expert of XML namespaces and it's the first time I see the use of absolute namespace in factur-x.xml. I sent a message to FNFE to ask if they want the validator to accept absolute namespaces like in your sample XML file... I'm waiting for their answer.

**Comment by alexis-via** [comment]
The FNFE was positive about the support for absolute namespaces, so I updated the code of the factur-x validator to support it. While working on it, I figured out your contribution to support absolute namespaces didn't take into account order-x not zugferd, so I fixed the regression.
Please reopen the bug report if it doesn't work in release 3.6 or if you find a problem with it.
