### ISSUE TITLE
Not valid against the official XML-Schema

### ISSUE THREAD

**Issue by MKorost** [akretion/factur-x#6]
Greetings,

so I'm having a problem for over a week now.

This is the error-message I'm getting: 

 `Exception: The Factur-x XML file is not valid against the official XML Schema Definition.
Here is the error, which may give you an idea on the cause of the problem:
Element '{urn:ferd:CrossIndustryDocument:invoice:1p0}CrossIndustryDocument':
No matching global declaration available for the validation root., line 2.`

Thanks in advance.

**Comment by MKorost** [comment]
Thanks for your fast answer.

The Issue is that the script doesn't generate any document.

This is the XML file i used for testing the script:
[https://github.com/konik-io/konik/blob/master/src/test/resources/ZUGFeRD-invoice.sample.xml](url)

**Comment by lucas-gp** [comment]
What function do you use? Generate, extract, or XML Check? Command line?

Anyway, the XML is valid

Why using ZUGFeRD? Factur-X (ZUGFeRD 2.0) has offficial examples and a complete documentation, version 1.1 is out today, with English documentation (you're lucky :))
Link Factur-X official documentation : http://fnfe-mpe.org/factur-x/factur-x_en/

**Comment by MKorost** [comment]
I'm using the function: 

`generate_facturx_from_file`

The reason why I use ZUGFeRD is because my internship supervisor gave me the task to write a program/script which can implement XML-files into PDFs as a ZUGFeRD-invoice.

-------------------------------------------------------------------------------------------------------------------

>  Factur-X (ZUGFeRD 2.0) has offficial examples and a complete documentation, version 1.1 is out today, with English documentation (you're lucky :))

I guess you're right, i'll try to use the documentation link you posted.
I'll come back if i have more issues.

Thanks for your help.
