### ISSUE TITLE
The comment, classifying the file as containing 8-bit binary data, is missing

### ISSUE THREAD

**Issue by scaf13** [akretion/factur-x#8]
Hi,

After generate a factur-x with the perl command-line "facturx-pdfgen", I got a error validation on https://www.pdf-online.com/osa/validate.aspx :

_Validating file "FA-2250-195153.xml.pdf" for conformance level pdfa-3b
The file header format does not conform to the standard.
**The comment, classifying the file as containing 8-bit binary data, is missing.**
The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted.
The document's meta data is either missing or inconsistent or corrupt.
**The document does not conform to the PDF/A-3b standard.**
Done._

It seem missing "%âãÏÓ" in the 2nd line of the pdf.

More info here : https://forums.adobe.com/thread/2419888

**Comment by alexis-via** [comment]
Should be fixed with the switch to pyPDF4 that was made in v1.0 released on 2019-01-26. Please re-open if it is not the case.
